language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - laravel="~5.1.0"
  - laravel="~5.2.0"
  - laravel="~5.3.0"
  - laravel="~5.4.0"

matrix:
  exclude:
    - php: 5.5
      env: laravel="~5.3.0"
    - php: 5.5
      env: laravel="~5.4.0"

cache:
  directories:
    - $HOME/.composer/cache

install: travis_retry composer require laravel/framework $laravel

script:
  - vendor/bin/phpunit
  - php vendor/bin/ocular code-coverage:upload --format=php-clover tests/reports/clover.xml
